### ISSUE TITLE
Bokeh Build: confirm connect to Saucelabs and SSH out

### ISSUE THREAD

**Issue by stephenakearns** [Binstar/binstar-build#283]
From @bryevdv ....

It's probably not an issue, but worth mentioning: jobs do need to be able to e.g., connect out to SauceLabs, which is where our Selenium tests run. They also need to be able SSH out (we deploy docs in an automated fashion to pydata.org with fab)

**Comment by damianavila** [comment]
ping here... this is important for us (Bokeh) to start a migration...

**Comment by dsludwig** [comment]
There are no outbound firewall rules for the build workers - they can access any external service. There should not be any issue with this.
