### ISSUE TITLE
Bokeh Build: build conda package as input to subsequent build steps

### ISSUE THREAD

**Issue by stephenakearns** [Binstar/binstar-build#284]
from @bryevdv ....

Here's something that would be a killer feature for us: the ability to have a build job that executed first, that produces a conda package as a result, and then this conda package is then automatically available to be used by all the remaining test jobs. Right now we spend 4 minutes on the front of every job downloading dependencies and compiling coffeescript, with the result that we build the same no-arch package 10 times.

**Comment by bollwyvl** [comment]
> Right now we spend 4 minutes on the front of every job downloading dependencies and compiling coffeescript

This. Also [this](https://github.com/conda/conda/issues/2391).

Perhaps in broadening the discussion about timed builds, having "agent" builds like this would let builds be chained in a reactive fashion. I guess one could break up bokeh into, say, `bokeh-js`, `bokeh-pypi`, `bokeh-conda`, `bokeh-docs` and `bokeh-site`. 

Each could be built one or more of the following:
- as triggered!
- as part of the source tree changing in a push: `src: bokehjs/`
- as a named point in the history changes: `git_ref: master`
- in response to another package being built: `upstream: [bokeh-js]`

And do things like:
- build!
- run tests
- push to `npm`, `pypi`, oh, and conda :)
- upload to s3/whatever

This provenance would become part of the history of the build, very handy indeed for reproducibility!

Interesting here is that one could actually imagine linking to external upstreams, even prior to a real release.

For example, on the notebook extensions, it would be nice to be able to able to re-run tests when any upstream (or upstream of upstream) is published: jupyter's dependency on `mistune` has bitten me on more than one occasion.

Or, in another scenario, one could imagine tracking two projects under heavy development for compatibility, basically building the cartesion product of active pull requests. Gross, but maybe very useful around coordinated build times (feature trains, etc).

This model sure sounds like a graph problem: networkx, odo, hierarchical finite state machines, or something more data-driven like JSON-LD would be interesting ways to capture these relationships. Very interesting stuff!

**Comment by bollwyvl** [comment]
@stephenakearns, @damianavila after our discussion of [airflow](https://github.com/airbnb/airflow), and while waiting for builds, i dusted off my trusty inkscape and set about imagining what this might be like for our favorite case, bokeh. This is part of my vision of Directory Services, @mmarchetti, but I didn't have a good example.

Basically, thinking about "work" as a series of activities with inputs and outputs, we can model finite-duration tasks... or continuous activities that emit discrete events.

This is not complete, but here are some thoughts:

![map](https://cloud.githubusercontent.com/assets/45380/14858856/a8732cae-0c6f-11e6-8219-7e74220825fd.png)

Imagining a phosphor + bokeh + d3 + [webcola](http://marvl.infotech.monash.edu/webcola/) kinda of thing. The bokeh stuff would show nicely, as at any point in this graph, you'd be able to dump to a dataframe. Under the hood, of course this is just updating some jinja+YAML.

Beyond the use case of _build complex software for many platforms,_ these primitive would also give us:
- _run monthly report_
- _publish website_
- _run survey_
- _initiate A/B test and report after x uses_

Fun stuff!
