### ISSUE TITLE
Bokeh Build: Scheduled (nightly) Builds

### ISSUE THREAD

**Issue by stephenakearns** [Binstar/binstar-build#285]
From @bryevdv ....

Another feature that would distinguish AS for us would be to have "nightly" jobs. We would like to dramatically increase some of out Selenium and image diff testing, but there is no way we could do it on every commit, it's just too expensive. It would be good to be able to have "overnight" jobs that run much longer test suites.

**Comment by damianavila** [comment]
I have also requested this previously (to have nightly jobs for Jupyter packages) so a :+1:
