### ISSUE TITLE
binstar-build does not accept `about: readme:` in `meta.yaml`

### ISSUE THREAD

**Issue by faph** [Binstar/binstar-build#32]
The binstar-build clients seems to suggest that the following is invalid inside the conda `meta.yaml`

``` yaml
about:
   - readme: Readme.md
```

Although this option is not documented (possibly a reason why there's so little detail on packages on binstar.org), it works perfectly fine in a local conda build.

I'm sure there's valid reasons why binstar-build checks `meta.yaml` but should it not be primarily up to conda build to decide what's valid and what's not. Not sure if the `readme` option is relatively new to conda build?

**Comment by tswicegood** [comment]
The README code is relatively new to conda-build (committed 17 days ago here https://github.com/conda/conda-build/commit/3f0a3a6e72cab2ff9c441f1309d42f85f72a0a81), so I imagine that's part of the issue.  One trick I've found is to include a `conda update --name=root conda-build` just to make sure that it's always on the latest.

That said, I'm assuming that binstar-build failed when running conda-build and not something before that.  Can you post a link to the build that failed?

**Comment by faph** [comment]
<https://binstar.org/openhydrology/autostatistical/builds/3/0>
 
Ah, yes, correct my fault, thanks! It is simply `conda build .` failing. I'd just assumed that it must have been the binstar client because my local build was ok. Didn't realise the readme was a new thing and also assumed that the binstar.org worker's conda was up to date. Many thanks for your help! Next time I'll use my own brain rather than assume things!
